import Head from 'next/head'
import {Box} from "../Components/Box"
import { ButtonClose } from '@/Components/ButtonClose'



export default function Home() {
  return (
    <>
      <Head>
        <title>Animated Navigatio Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box></Box>
     
    </>
  )
}
